# Site settings
title: MgCoders Blog
email: info@mgcoders.com
description: > # this means to ignore newlines until "baseurl:"
 Por ahora mgcoders.uy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mgcoders.uy" # the base hostname & protocol for your site
twitter_username: mgcoders
github_username:  mgcoders

# Build settings
markdown: kramdown
